"""empty message

Revision ID: 15e41d582d44
Revises: 93dc787d2942
Create Date: 2022-07-04 13:51:15.703582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e41d582d44'
down_revision = '93dc787d2942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartoes')
    op.add_column('gastos', sa.Column('meio', sa.Integer(), nullable=True))
    op.drop_constraint('gastos_cartao_id_fkey', 'gastos', type_='foreignkey')
    op.drop_column('gastos', 'cartao_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos', sa.Column('cartao_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('gastos_cartao_id_fkey', 'gastos', 'cartoes', ['cartao_id'], ['id'])
    op.drop_column('gastos', 'meio')
    op.create_table('cartoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cartao', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('data_vencimento', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cartoes_pkey')
    )
    # ### end Alembic commands ###
