"""tentando sssssadicionar coluna de usuario.

Revision ID: 3c735be6be6e
Revises: 05235795c1ba
Create Date: 2022-06-29 14:19:25.723704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c735be6be6e'
down_revision = '05235795c1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos', sa.Column('usuario', sa.Integer(), nullable=True))
    op.drop_constraint('gastos_UserControl_id_fkey', 'gastos', type_='foreignkey')
    op.create_foreign_key(None, 'gastos', 'usuarios_control', ['usuario'], ['id'])
    op.drop_column('gastos', 'UserControl_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos', sa.Column('UserControl_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'gastos', type_='foreignkey')
    op.create_foreign_key('gastos_UserControl_id_fkey', 'gastos', 'usuarios_control', ['UserControl_id'], ['id'])
    op.drop_column('gastos', 'usuario')
    # ### end Alembic commands ###
