"""empty message

Revision ID: 93dc787d2942
Revises: 
Create Date: 2022-07-03 17:01:41.297096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93dc787d2942'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios_control', sa.Column('meios', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios_control', 'meios')
    # ### end Alembic commands ###
